theme: jekyll-theme-minimal

title: Zhuang Linsheng
logo: https://zhuanglinsheng.github.io/res/cv/Me.jpg
show_downloads: false
description: Welcome to Linsheng's personal site. Here is my <a href="https://zhuanglinsheng.github.io/res/cv/cv2020.pdf">CV (2020)</a>.
