title: Zhuang Linsheng
show_downloads: false
description: Homepage
url: https://zhuanglinsheng.github.io
baseurl: /zhuanglinsheng.github.io
github_username: zhuanglinsheng

plugins:
  - jekyll-feed

feed:
  tags: true
  posts_limit: 1000
