theme: jekyll-theme-minimal

title: Zhuang Linsheng
logo: https://zhuanglinsheng.github.io/res/Me.jpg
show_downloads: false
description: I am currently a PhD student of National University of Singapore Institute of Operations Research and Analytics (IORA). My research interest is broad, including numerical methods, optimization, stochastic modelling and control. Here is my <a href="https://zhuanglinsheng.github.io/res/cv/cv2020.pdf">CV (2020)</a>.
